language:
  ruby 2.3.0
before_install:
  - gem update --system
  - gem --version
env:
  - DB=postgresql
addons:
  postgresql: "9.5.4:"
before_script:
  - bundle install
  - bundle exec rake db:setup
  - RAILS_ENV=test bundle exec rake db:seed
script:
  - bundle exec cucumber
  - bundle exec rspec  
notifications: # set notification options
  email:
    recipients:
      - one@example.com


    # change is when the repo status goes from pass to fail or vice versa
    on_success: [always|never|change]
    on_failure: [always|never|change]
  # Or we could just disable all email
  email: false

before_deploy:
- gem install mime-types -v 2.6.2
# deploy:
#   provider: heroku
#   api_key:
#   app:
#     master:my-app
#     sprint1
#     sprint2
#     sprint3
